name: commit_info
description: Safely get version control information in a Dart project.
version: 0.0.1
license: MIT
homepage: https://github.com/lalomartins/dart-commit-info

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  path: ^1.8.3

dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.4.6
  pedantic: ^1.11.1
  test: ^1.24.6

executables:
  initialize:
